# config

# interval in mins
interval: 50
course_type: "3A"
query_months: ["202211", "202212"]

accounts:
  - username: "123A01012000"
    password: "114514"
    chat_id: "512345678"
    preferred_slots: # optional
      # Currently Supported Slot Type:
      # "Practical"
      - slot_type: "Practical"
        date: "2022-11-11"
        sessions: [1, 2, 3]
      - slot_type: "Practical"
        date: "2022-12-12"
        sessions: [4, 5, 6]

telegram:
  token: "5123456789:asdfghjkl"
  broadcast_chat_id: "512345678" # can be the same as account chat_id
